#!/usr/bin/env bash

if [ ! -d ~/sketchbook ]
then
  echo "~/sketchbook directory not found, creating!"
  mkdir ~/sketchbook
else
  echo "~/sketchbook directory found"
fi
echo "Copying hardware definitions..."
cp -vr hardware ~/sketchbook/
echo "All done!"
